// ── Roommate matching enums ──

export const SLEEP_SCHEDULE = Object.freeze({
  EARLY_BIRD: 'EARLY_BIRD',
  NIGHT_OWL: 'NIGHT_OWL',
})

export const SOCIAL_HABITS = Object.freeze({
  QUIET: 'QUIET',
  MODERATE: 'MODERATE',
  SOCIAL: 'SOCIAL',
})

export const STUDY_HABITS = Object.freeze({
  SILENT: 'SILENT',
  SOME_NOISE: 'SOME_NOISE',
  ANY: 'ANY',
})

export const AC_TYPE = Object.freeze({
  AC: 'AC',
  NON_AC: 'NON_AC',
})

export const ROOM_POSITION = Object.freeze({
  BALCONY: 'BALCONY',
  MIDDLE: 'MIDDLE',
})

export const AVAILABILITY_STATUS = Object.freeze({
  AVAILABLE: 'AVAILABLE',
  PARTIALLY_FILLED: 'PARTIALLY_FILLED',
  FULL: 'FULL',
  MAINTENANCE: 'MAINTENANCE',
})

export const MATCH_REQUEST_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  CANCELLED: 'CANCELLED',
})

export const NOTIFICATION_TYPE = Object.freeze({
  MATCH_REQUEST_RECEIVED: 'MATCH_REQUEST_RECEIVED',
  MATCH_REQUEST_ACCEPTED: 'MATCH_REQUEST_ACCEPTED',
  MATCH_REQUEST_REJECTED: 'MATCH_REQUEST_REJECTED',
  ROOMMATE_PAIR_LOCKED: 'ROOMMATE_PAIR_LOCKED',
  ROOM_CHANGED: 'ROOM_CHANGED',
  ISSUE_STATUS_UPDATED: 'ISSUE_STATUS_UPDATED',
})

export const ISSUE_CATEGORY = Object.freeze({
  FACILITIES: 'FACILITIES',
  SAFETY: 'SAFETY',
  ROOM_CONDITION: 'ROOM_CONDITION',
  CLEANING: 'CLEANING',
  ELECTRICITY: 'ELECTRICITY',
  WATER: 'WATER',
  OTHER: 'OTHER',
})

export const ISSUE_PRIORITY = Object.freeze({
  EMERGENCY: 'EMERGENCY',
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW',
})

export const ISSUE_STATUS = Object.freeze({
  SUBMITTED: 'SUBMITTED',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
})
